import type { Student } from "@/lib/types";

export const studentsSeed: Student[] = [
  {
    id: "ATI-2025-0101",
    name: "Aarav Sharma",
    course: "Master Diploma in Computer Technology",
    courseKey: "MDCT",
    batch: "2025",
    father: "Ramesh Sharma",
    phone: "+977 9841234567",
    address: "Ward 4, Birendranagar",
    school: "Model Higher Secondary School",
    prior: "+2 Science",
    score: 88,
    grade: "A+",
    attendance: 94,
    status: "Top Performer",
    teacher: "Suraj Bist",
    timing: "8-10 AM",
    weekly: [
      ["Week 1", "HTML/CSS", 48, 50, "06 Apr 2025"],
      ["Week 2", "JavaScript", 45, 50, "13 Apr 2025"],
      ["Week 3", "React Basics", 42, 50, "20 Apr 2025"],
      ["Week 4", "Node.js", 46, 50, "27 Apr 2025"],
    ].map(([label, subject, score, max, date]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: String(date),
    })),
    monthly: [
      ["Term I", "Computer Fundamentals", 92, 100],
      ["Term I", "Programming in C/C++", 86, 100],
      ["Term I", "Web Technology", 90, 100],
      ["Term I", "Database Systems", 84, 100],
    ].map(([label, subject, score, max]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: "May 2025",
    })),
    remarks:
      "Aarav shows exceptional logical skills and is consistently ahead in practical lab assignments.",
    admissionFee: 3000,
    courseFee: 45000,
    payments: [
      { id: "p1", amount: 20000, date: "27 Chaitra 2081", mode: "Cash" },
      { id: "p2", amount: 15000, date: "27 Jestha 2082", mode: "Bank Transfer" },
    ],
  },
  {
    id: "ATI-2025-0102",
    name: "Priya Adhikari",
    course: "Python Programming & Data Science",
    courseKey: "Python",
    batch: "2025",
    father: "Hari Prasad Adhikari",
    phone: "+977 9851098765",
    address: "Main Road, Surkhet",
    school: "Horizon Higher Secondary School",
    prior: "+2 Management",
    score: 76,
    grade: "B+",
    attendance: 88,
    status: "Good",
    teacher: "Neha Bist",
    timing: "10-12 PM",
    weekly: [
      ["Week 1", "Python Syntax", 40, 50, "06 Apr 2025"],
      ["Week 2", "Data Structures", 38, 50, "13 Apr 2025"],
      ["Week 3", "Pandas/Numpy", 37, 50, "20 Apr 2025"],
      ["Week 4", "OOP Concepts", 39, 50, "27 Apr 2025"],
    ].map(([label, subject, score, max, date]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: String(date),
    })),
    monthly: [
      ["Term I", "Core Python", 78, 100],
      ["Term I", "Data Analysis", 72, 100],
      ["Term I", "Statistics", 75, 100],
      ["Term I", "SQL Basics", 79, 100],
    ].map(([label, subject, score, max]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: "May 2025",
    })),
    remarks:
      "Priya is working hard and grasping concepts well. Extra practice on data analysis projects will boost her performance.",
    admissionFee: 3000,
    courseFee: 38000,
    payments: [{ id: "p1", amount: 15000, date: "25 Chaitra 2081", mode: "Cash" }],
  },
  {
    id: "ATI-2025-0103",
    name: "Rohan Karki",
    course: "UI/UX & Graphic Design",
    courseKey: "Graphic Design",
    batch: "2024",
    father: "Bikram Karki",
    phone: "+977 9803456789",
    address: "Housing Colony, Birendranagar",
    school: "National Technical Institute",
    prior: "Grade 10 (SEE)",
    score: 62,
    grade: "C+",
    attendance: 72,
    status: "Needs Attention",
    teacher: "Ravi Bist",
    timing: "2-4 PM",
    weekly: [
      ["Week 1", "Figma Tools", 35, 50, "06 Apr 2025"],
      ["Week 2", "Color Theory", 30, 50, "13 Apr 2025"],
      ["Week 3", "Typography", 28, 50, "20 Apr 2025"],
      ["Week 4", "Wireframing", 32, 50, "27 Apr 2025"],
    ].map(([label, subject, score, max, date]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: String(date),
    })),
    monthly: [
      ["Term I", "Vector Graphics", 60, 100],
      ["Term I", "UI Layouts", 64, 100],
      ["Term I", "Design Systems", 58, 100],
      ["Term I", "User Research", 66, 100],
    ].map(([label, subject, score, max]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: "May 2025",
    })),
    remarks:
      "Rohan has great creative potential, but needs to improve attendance and submit weekly design tasks on time.",
    admissionFee: 3000,
    courseFee: 32000,
    payments: [],
  },
  {
    id: "ATI-2025-0104",
    name: "Sneha Thapa",
    course: "Web Development & Hardware",
    courseKey: "Web Dev",
    batch: "2025",
    father: "Dhan Bahadur Thapa",
    phone: "+977 9812987654",
    address: "Airport Area, Surkhet",
    school: "Valley Public School",
    prior: "+2 Science",
    score: 83,
    grade: "A",
    attendance: 91,
    status: "Top Performer",
    teacher: "Suraj Bist",
    timing: "2-4 PM",
    weekly: [
      ["Week 1", "Hardware Assembly", 45, 50, "06 Apr 2025"],
      ["Week 2", "Networking", 42, 50, "13 Apr 2025"],
      ["Week 3", "Tailwind CSS", 41, 50, "20 Apr 2025"],
      ["Week 4", "JavaScript ES6", 40, 50, "27 Apr 2025"],
    ].map(([label, subject, score, max, date]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: String(date),
    })),
    monthly: [
      ["Term I", "Computer Hardware", 88, 100],
      ["Term I", "Network Security", 80, 100],
      ["Term I", "Responsive Web Design", 84, 100],
      ["Term I", "Frontend Frameworks", 80, 100],
    ].map(([label, subject, score, max]) => ({
      label: String(label),
      subject: String(subject),
      score: Number(score),
      max: Number(max),
      date: "May 2025",
    })),
    remarks: "Sneha is very consistent in both theory and practical lab sessions.",
    admissionFee: 3000,
    courseFee: 40000,
    payments: [
      { id: "p1", amount: 20000, date: "22 Chaitra 2081", mode: "Bank Transfer" },
      { id: "p2", amount: 20000, date: "20 Ashadh 2082", mode: "Bank Transfer" },
    ],
  },
];
